import("nvim-mini/mini.nvim")
require("mini.icons").setup()
require("mini.statusline").setup()
require("plugins.telescope")
require("plugins.around")
require("plugins.autopairs")
require("plugins.completion")
require("plugins.flash")
require("plugins.which-key")
require("plugins.todo-comments")
require("plugins.surround")
require("plugins.snippets")
require("plugins.harpoon")
require("plugins.buffer-tabs")
require("plugins.comment")
require("plugins.nvim-tree")
--require("plugins.files")
-- require("plugins.map")
-- require("plugins.animate")
